export const SOCKET_EVENT = {
  JOIN_BOARD: "joinBoard",
  LEAVE_BOARD: "leaveBoard",
  LIST_CREATED: "listCreated",
  LIST_UPDATED: "listUpdated",
  LIST_MOVED: "listMoved",
  LIST_DELETED: "listDeleted",
  CARD_CREATED: "cardCreated",
  CARD_UPDATED: "cardUpdated",
  CARD_MOVED: "cardMoved",
  CARD_DELETED: "cardDeleted",
  CARD_ASSIGNEE_CHANGED: "cardAssigneeChanged",
  COMMENT_ADDED: "commentAdded",
  CHECKLIST_ITEM_TOGGLED: "checklistItemToggled",
  ATTACHMENT_ADDED: "attachmentAdded",
  LABEL_CREATED: "labelCreated",
  LABEL_UPDATED: "labelUpdated",
  LABEL_DELETED: "labelDeleted",
  NOTIFICATION_CREATED: "notificationCreated",
  BOARD_MEMBER_REMOVED: "boardMemberRemoved",
} as const;
